/*
In 1953, David A. Huffman published his paper "A Method for the Construction of Minimum-Redundancy Codes", and hence printed his name in the history of computer science. As a professor who gives the final exam problem on Huffman codes, I am encountering a big problem: the Huffman codes are NOT unique. For example, given a string "aaaxuaxz", we can observe that the frequencies of the characters 'a', 'x', 'u' and 'z' are 4, 2, 1 and 1, respectively. We may either encode the symbols as {'a'=0, 'x'=10, 'u'=110, 'z'=111}, or in another way as {'a'=1, 'x'=01, 'u'=001, 'z'=000}, both compress the string into 14 bits. Another set of code can be given as {'a'=0, 'x'=11, 'u'=100, 'z'=101}, but {'a'=0, 'x'=01, 'u'=011, 'z'=001} is NOT correct since "aaaxuaxz" and "aazuaxax" can both be decoded from the code 00001011001001. The students are submitting all kinds of codes, and I need a computer program to help me determine which ones are correct and which ones are not.
Input Specification:

Each input file contains one test case. For each case, the first line gives an integer N (2≤N≤63), then followed by a line that contains all the N distinct characters and their frequencies in the following format:

c[1] f[1] c[2] f[2] ... c[N] f[N]

where c[i] is a character chosen from {'0' - '9', 'a' - 'z', 'A' - 'Z', '_'}, and f[i] is the frequency of c[i] and is an integer no more than 1000. The next line gives a positive integer M (≤1000), then followed by M student submissions. Each student submission consists of N lines, each in the format:

c[i] code[i]

where c[i] is the i-th character and code[i] is an non-empty string of no more than 63 '0's and '1's.
Output Specification:

For each test case, print in each line either "Yes" if the student's submission is correct, or "No" if not.

Note: The optimal solution is not necessarily generated by Huffman algorithm. Any prefix code with code length being optimal is considered correct.
Sample Input:

7
A 1 B 1 C 1 D 3 E 3 F 6 G 6
4
A 00000
B 00001
C 0001
D 001
E 01
F 10
G 11
A 01010
B 01011
C 0100
D 011
E 10
F 11
G 00
A 000
B 001
C 010
D 011
E 100
F 101
G 110
A 00000
B 00001
C 0001
D 001
E 00
F 10
G 11

Sample Output:

Yes
Yes
No
No


*/


#include <stdio.h>
#include <stdlib.h>

typedef struct TNode *HuffmanTree;
typedef struct TNode *Tree;

struct TNode{
    int weight;
	struct TNode* Left;
    struct TNode* Right;
};


#define		MaxSize		1001
typedef struct TNode ElemType;

typedef struct HNODE *Heap;
struct HNODE {
	ElemType *Data;
	int Size;
	int Capacity;
};

#define  MINDATA 0

typedef Heap    MaxHeap;
typedef Heap    MinHeap;


MaxHeap CreateHeap(int maxsize);
void DisplayHeap(MinHeap H);
void FreeHeap(MinHeap H);
int IsFull(MinHeap H);
int IsEmpty(MinHeap H);
int Insert(MinHeap H, ElemType X);
ElemType* DeleteMin(MinHeap H);





//////////////////////////////////////////////////

HuffmanTree Huffman(MinHeap H);
void PreorderTraversal( HuffmanTree BT ); 
int WPL(HuffmanTree HT, int depth);
int Judge(int aCnt, int hCode, char text[], int hz[]);
Tree BuildTree();
void DestroyTree(Tree T);
int JudgeTree(Tree T, int Hz);

int main()
{
    MinHeap H;
    int N, M, i;
    char *pText;
    int *pHz;
    ElemType *pelem;
    HuffmanTree T;
	int huffmanCodeLen;
    scanf("%d", &N);
	getchar();
    pText = (char*)malloc(sizeof(char)*N);
    pHz = (int*)malloc(sizeof(int)*N);
    
    H = CreateHeap(N);
	for (i = 0; i < N; i ++)
    {
        scanf("%c ", pText+i);
        if (i == (N-1))
            scanf("%d", pHz+i);
        else
            scanf("%d ", pHz+i);
        pelem = malloc(sizeof(ElemType));
        pelem->weight = *(pHz+i);
        pelem->Left = NULL;
        pelem->Right = NULL;
        Insert(H, *pelem);
    }
 //   DisplayHeap(H);
    T = Huffman(H);
  //  PreorderTraversal(T); 
	fflush(stdout);
	huffmanCodeLen = WPL(T, 0);
//	printf("codelen = %d\n", huffmanCodeLen);
	scanf("%d", &M);
	while (M --)
	{
		if (Judge(N, huffmanCodeLen, pText, pHz))printf("Yes\n");
		else printf("No\n");
	}
	
    free(pHz);
    free(pText);
    FreeHeap(H);
    
	fflush(stdout);
    return 0;
}

char answer[MaxSize];

Tree BuildTree()
{
	Tree elem = malloc(sizeof(struct TNode));
	elem->weight = 0;
	elem->Right = elem->Left = NULL;

	return elem;
}

int JudgeTree(Tree T, int Hz)
{
	int len = strlen(answer);
	int i;
	Tree CurT = T;

	for (i = 0; i < len; i++)
	{
		if (answer[i] == '1')
		{
			if (CurT->Right == NULL)
			{
				Tree TempT = malloc(sizeof(struct TNode));
				TempT->Left = TempT->Right = NULL;
				TempT->weight = 0;
				CurT->Right = TempT;
			}
			else if (CurT->Right->weight != 0)
			{
				return 0;
			}
			CurT = CurT->Right;
		}
		if (answer[i] == '0')
		{
			if (CurT->Left == NULL)
			{
				Tree TempT = malloc(sizeof(struct TNode));
				TempT->Left = TempT->Right = NULL;
				TempT->weight = 0;
				CurT->Left = TempT;
			}
			else if (CurT->Left->weight != 0)
			{
				return 0;
			}
			CurT = CurT->Left;
		}
	}
	
	////有误
	//if (CurT->weight != 0)
	//{
	//	return 0;
	//}
	if (CurT->Left == NULL && CurT->Right == NULL)
	{
		CurT->weight = Hz;
		return 1;
	}
	else
		return 0;
	
//	return 1;
}



void DestroyTree(Tree T)
{

	if (T != NULL)
	{
		//		printf("%d ", BT->weight);
		DestroyTree(T->Left);
		DestroyTree(T->Right);
		free(T);
	}
	
}




int Judge(int aCnt, int hCode, char text[], int hz[])
{
	int i, len, wpl = 0, N = aCnt, j;
	int skip = 1;
	char s1[2];
	Tree T = BuildTree();
	for (i = 0; i < aCnt; i++)
	{
		if (!skip)
		{
			scanf("%s%s", s1, answer);
			continue;
		}
		scanf("%s%s", s1, answer);
		len = strlen(answer);
		if (len > N)
		{
			skip = 0;
			continue;
		}
		for (j = 0; s1[0] != text[j]; j++);
		if (j >= N)
		{
			skip = 0;
			continue;
		}
		wpl += hz[j] * len;
		skip = JudgeTree(T, hz[j]);
	}
	DestroyTree(T);
	if (skip == 0)
	{
		return 0;
	}
	if (wpl != hCode)
	{
		return 0;
	}

	return 1;
}

HuffmanTree Huffman(MinHeap H)
{
    int i; 
    HuffmanTree T;

    while(!IsEmpty(H)) {
        T = malloc(sizeof(struct TNode));
        T->Left = DeleteMin(H);      
        T->Right = DeleteMin(H);  
        T->weight = T->Left->weight+T->Right->weight;   
		if (!IsEmpty(H))  //当堆空的时候 就完成堆的创建
			Insert(H, *T); 
    }

    return T;
}

//先序遍历树
void PreorderTraversal(HuffmanTree BT)
{

	if (BT != NULL)
	{
//		printf("%d ", BT->weight);
		PreorderTraversal(BT->Left);
		PreorderTraversal(BT->Right);
	}
}

//计算wpl
int WPL(HuffmanTree HT, int depth)
{
	if (!HT->Left && !HT->Right)
	{
		return (depth*HT->weight);
	}
	else
	{
		int lwpl = 0, rwpl = 0;
		lwpl = WPL(HT->Left, depth + 1);
		rwpl = WPL(HT->Right, depth + 1);

		return (lwpl+rwpl);
	}
}

MaxHeap CreateHeap(int maxsize)
{
    MinHeap H = (MinHeap)malloc(sizeof(struct HNODE));

    H->Data = (ElemType*)malloc((maxsize+1)*sizeof(ElemType));
    H->Size = 0;
    H->Capacity = maxsize;
   // H->Data[0] = MINDATA;

    return H;
}


void DisplayHeap(MinHeap H)
{
    int i;
    for (i = 1; i <= H->Size; i ++)
        printf("%d ", ((ElemType*)(H->Data+i))->weight);
    printf("\n");
}

int Insert(MinHeap H, ElemType X)
{
    int i;
    if (IsFull(H))
    {
        return 0;
    }
    i = ++H->Size;
    for(; H->Data[i/2].weight > X.weight; i/=2)
        H->Data[i] = H->Data[i/2];
    H->Data[i] = X;
    return 1;
}

void FreeHeap(MinHeap H)
{
    free(H->Data);
    free(H);
}

int IsFull(MinHeap H)
{
    return (H->Size == H->Capacity);
}


int IsEmpty(MinHeap H)
{
    
    return (H->Size == 0);
}

ElemType* DeleteMin(MinHeap H)
{
    int Parent, Child;

    ElemType  X;
    ElemType *pMinItem = malloc(sizeof(ElemType));

 //   if (IsEmpty(H)) {
 //       return ;
//    }
    *pMinItem = H->Data[1];
    X = H->Data[H->Size--];
    for (Parent = 1; Parent*2 <= H->Size; Parent = Child)
    {
        Child = 2*Parent;
        if((Child != H->Size)&&(H->Data[Child].weight > H->Data[Child+1].weight))
            Child ++;
        if (X.weight <= H->Data[Child].weight)
            break;
        else
            H->Data[Parent] = H->Data[Child];
    }
    H->Data[Parent] = X;
    return pMinItem;
}
